server:
  port: 7829

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pawan
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Shaik@7411
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
